=== nastiykr/FS/Lecture14/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Animal",
  "description": "My cat",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "animal_type": {
      "description": "Type of animal",
      "type": "string"
    },
    "name": {
      "description": "Name of the product",
      "type": "string"
    },
    "age": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "colors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "has_tail": {
      "type": "boolean"
    },
    "friends": {
      "type": "object",
      "properties": {
        "count": {
          "type": "number",
          "minimum": 0,
          "exclusiveMinimum": true
        }
      }
    }
  }
}

=== nastiykr/FS/Lecture14/src/main/resources/json2.json
[
  {
    "animal_type": "cat",
    "name": "Vasya",
    "age": 25,
    "has_tail": true,
    "colors": [
      "white",
      "orange",
      "black"
    ],
    "friends": {
      "count": 3
    }
  },
  {
    "animal_type": "turtle",
    "name": "Tortilla",
    "age": 100,
    "has_tail": true,
    "colors": [
      "dark_green"
    ],
    "friends": {
      "count": 5
    }
  }
]
